import iota_client
from pprint import pprint
import json


client = iota_client.Client()

# message_id is generated by upload.py
message_id = "de0fd1f84761dd740b5c06082cb098031f2bd0bf30dd621155e1807ffe993eb6"

# print(f'get_message_raw() for message_id {message_id}')
message_raw = client.get_message_raw(message_id)
# print(f"raw_data = {message_raw}")

data_str = message_raw[message_raw.index("name")-1:message_raw.index("}")]
pprint(f"data = {data_str}")
# output = json.loads(data)
# pprint(str(output))
data_dict = dict((a.strip("'"), (b.strip("'")))
                 for a, b in (element.split(': ')
                              for element in data_str.split(', ')))
print(f"{type(data_dict)}, {data_dict}")

with open("sample.json", "w") as outfile:
    json.dump(data_dict, outfile)
